name: Docker and Kubernetes CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t todo-app:latest .

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Deploy to Minikube
      run: |
        eval $(minikube docker-env)
        docker build -t todo-app:latest .
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/todo-app 